### ISSUE TITLE
More usable search component

### ISSUE THREAD

**Issue by Mert18** [Mert18/hachiko-dictionary#76]
The search component on the home screen should be changed.

It currently shows the results when user presses "enter". We might want to implement a better solution: when the input component is active, send the search request every second. But the request should not be sent when user not searching.

**Comment by Fury-MadMax** [comment]
I didn't get your issue can you please describe once again and it will be better if you add screenshots and screen recording of the issue

**Comment by Mert18** [comment]
I have updated the description. 

But this issue require you to log in to the application and you need to run the backend on your local machine.

In order to do it you can follow the instructions on the README.md but the instructions are not updated with the latest changes(I have migrated the db from PostgreSQL to MongoDB). I will update them shortly, then you will be able to run the backend with one command and log in to the application on your local machine.

Please check this issue after a few days. I will update the README.md file shortly.

**Comment by Mert18** [comment]
Hello again, I have updated it. You can now easily set up and run backend service following the instructions. Then you can login with test credentials "test@gmail.com" "test123". Then you will see the search bar and can do the task. Thank you.

**Comment by Mert18** [comment]
As I do not want to make it just a regular dictionary, I decided to remove search component from the application. I am sorry if you are still working on it.
