### ISSUE TITLE
main page, words overflow in small screens

### ISSUE THREAD

**Issue by Mert18** [Mert18/hachiko-dictionary#90]
![image](https://github.com/Mert18/hachiko-dictionary/assets/40024436/b1c88b52-a5d1-42f7-b2c7-fdfd845cc01e)

**Comment by GeorgiosDrivas** [comment]
Hello! I believe this has to do with the responsiveness of the website. I would like to work on this issue.

**Comment by Mert18** [comment]
You can send the pr. You're welcome.
